version: '3'
services:
  mysql:
    image: mariadb:10.4
    volumes:
      - mysql-db-data:/var/lib/mysql
      #- "./data/db:/var/lib/mysql"
    ports:
      - "3306:3306"
    restart: always
    #command: --default_authentication_plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=sume
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
  laravel-env:
    build: ./dockerfiles
    depends_on:
      - mysql
    ports:
      - 9000
    volumes:
      - "./backend-api-laravel:/var/www/sume"
      - "./dockerfiles/bin:/var/www/dockerfiles/bin"
      - "./dockerfiles/config/php/php-fpm.conf:/etc/php-fpm.conf"
      - "./dockerfiles/config/php/www.conf:/etc/php-fpm.d/www.conf"
      - "./dockerfiles/config/php/php.ini:/usr/local/etc/php/php.ini"
      - "./dockerfiles/config/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
  nginx:
    image: nginx:latest
    depends_on:
      - laravel-env
    volumes:
      - "./backend-api-laravel:/var/www/sume"
      - "./dockerfiles/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    restart: always
  vue:
    build: ./dockerfiles/vue
    volumes:
      - "./frontend-vue:/app"
      - "./dockerfiles/bin:/dockerfiles/bin"
    ports:
      - 8080
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=sume
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - "./data/mongodb:/data/db"
    ports:
      - 27017:27017
    logging:
      driver: none

volumes:
  mysql-db-data:
