export default {
  computed: {
    fieldsInfo () {
      return [
        {
          text: this.$t('fields.id'),
          name: 'id',
          details: false,
          table: false,
        },
        {
          type: 'input',
          column: 'name',
          text: this.$t('fields.name'),
          grid: 'xs12 sm6 md4 lg6 xl4',
          name: 'name',
          multiedit: false,
        },
        {
          type: 'input',
          column: 'business_name',
          text: this.$t('fields.businessName'),
          grid: 'xs12 sm6 md4 lg6 xl4',
          name: 'businessName',
          apiObject: {
            name: 'business_name',
          },
          multiedit: false,
        },
        {
          type: 'select',
          url: 'crud/companies/company-types',
          list: {
            value: 'id',
            text: 'name',
            data: [],
          },
          column: 'company_type_id',
          text: this.$t('fields.companyType'),
          grid: 'xs12 sm6 md4 lg6 xl4',
          name: 'companyType',
          apiObject: {
            name: 'company_type.name',
          },
        },
        {
          type: 'select',
          url: 'crud/system/countries',
          list: {
            value: 'code',
            text: 'name',
            data: [],
          },
          column: 'country_code',
          text: this.$t('fields.countryCode'),
          grid: 'xs6 sm3 md2 lg3 xl2',
          name: 'country',
          apiObject: {
            name: 'country.code',
          },
          multiedit: false,
          table: false,
        },
        {
          type: 'input',
          column: 'email',
          text: this.$t('fields.email'),
          grid: 'xs12 sm6 md4 lg6 xl4',
          name: 'email',
          create: false,
          multiedit: false,
          required: false,
        },
        {
          type: 'input',
          column: 'single_tax_identification_number',
          text: this.$t('fields.singleTaxIdentificationNumber'),
          grid: 'xs12 sm6 md4 lg6 xl4',
          table: false,
          create: false,
          multiedit: false,
          required: false,
        },
        {
          type: 'input',
          column: 'web_page',
          text: this.$t('fields.webPage'),
          grid: 'xs12 sm6 md4 lg6 xl4',
          table: false,
          create: false,
          multiedit: false,
          required: false,
        },
        {
          type: 'input',
          column: 'coordinates_lat',
          text: this.$t('fields.coordinatesLat'),
          grid: 'xs12 sm6 md4 lg6 xl4',
          table: false,
          create: false,
          multiedit: false,
          required: false,
        },
        {
          type: 'input',
          column: 'coordinates_lng',
          text: this.$t('fields.coordinatesLng'),
          grid: 'xs12 sm6 md4 lg6 xl4',
          table: false,
          create: false,
          multiedit: false,
          required: false,
        },
      ]
    },
  },
}
